name: GLB File Update Automation

on:
  push:
    branches:
      - 'assets-glb'
    paths:
      - 'assets/models/*.glb'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Parse FTP Credentials
        id: ftp_creds
        shell: bash
        run: |
          echo '${{ secrets.SIMPLE_FTP }}' > ftp_creds.json
          server=$(jq -r '.[0].host' ftp_creds.json)
          username=$(jq -r '.[0].username' ftp_creds.json)
          password=$(jq -r '.[0].password' ftp_creds.json)
          echo "server=$server" >> $GITHUB_OUTPUT
          echo "username=$username" >> $GITHUB_OUTPUT
          echo "password=$password" >> $GITHUB_OUTPUT

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ steps.ftp_creds.outputs.server }}
          username: ${{ steps.ftp_creds.outputs.username }}
          password: ${{ steps.ftp_creds.outputs.password }}
          protocol: ftp
          local-dir: assets/models
          server-dir: /assets/models
          concurrency: 10
          security: false
